ALTER TABLE sales_orders
ADD COLUMN IF NOT EXISTS customer_id INTEGER REFERENCES entities(id),
ADD COLUMN IF NOT EXISTS customer_po_number VARCHAR(100),
ADD COLUMN IF NOT EXISTS total_amount DECIMAL(15, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS created_by INTEGER,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();

\d sales_orders
